try {
  throw "this is called";
  callMyFunction();
} catch (error) {
  console.log(error);
}
